name = "miaomiao-config"
main = "worker.js"
compatibility_date = "2026-08-01"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "cdn.vpnmiao.com/manifest.json", zone_name = "vpnmiao.com" },
  { pattern = "cdn.vpnmiao.com/manifest.json/*", zone_name = "vpnmiao.com" },
  { pattern = "cdn.vpnmiao.com/json", zone_name = "vpnmiao.com" },
  { pattern = "cdn.vpnmiao.com/json/*", zone_name = "vpnmiao.com" }
]
